logging:
    level:
        org: INFO

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:63306/social?connectTimeout=0&socketTimeout=0&autoReconnect=true
        name:
        username: social
        password: social
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false