# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

jhipster:
    social:
        redirectAfterSignIn: "/#/home"

    security:
        rememberMe:
            # security key (this key should be unique for your application, and kept secret)
            key: b25db65c2bb1deab99a949ca86018da4ea5bdc01


# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
    level:
        org: DEBUG

management:
    context-path: /management

spring:
    application:
        name: social
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:social;DB_CLOSE_DELAY=-1
        name:
        username: social
        password:
    h2:
        console:
            enabled: false
    jpa:
        database-platform: cz.akineta.example.social.FixedH2Dialect
        database: H2
        show-sql: true
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true

    social:
        # see https://developers.google.com/+/web/signin/server-side-flow#step_1_create_a_client_id_and_client_secret
        google:
            clientId: xxx
            clientSecret: xxx

        # see https://developers.facebook.com/docs/facebook-login/v2.2
        facebook:
            clientId: xxx
            clientSecret: xxx

        # see https://apps.twitter.com/app/
        twitter:
            clientId: xxx
            clientSecret: xxx

        # jhipster-needle-add-social-configuration

security:
    basic:
        enabled: false

server:
    session:
        cookie:
            http-only: true